name: responsive_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # state management
  stacked: ^3.0.1
  stacked_services: ^0.9.9

  #ui
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/